apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-chart.fullname" . }}-app-config
data:
  app.conf: |-
{{ .Files.Get (printf "conf/%s/app.conf" .Values.environment) | indent 4 }}
