apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tomcatcharts.fullname" . }}-app-config
data:
  app.conf: |-
{{ .Files.Get (printf "tomcatcharts/conf/%s/app.conf" .Values.environment) | indent 4 }}
