apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tomcatimage
  namespace: tomcatcharts
spec:
  interval: 1m
  chart:
    spec:
      chart: tomcatcharts
      version: "1.2.3"  # Replace with the desired chart version
      sourceRef:
        kind: GitRepository
        name: newinfra  # Refer to the HelmRepository defined above
        namespace: flux-system
      valuesFiles:
        - tomcatcharts/values.yaml

  install:
    createNamespace: true
  rollback:
    force: true
