apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tomcatimage
  namespace: tomcatcharts
spec:
  interval: 1m
  chart:
    spec:
      chart: tomcatcharts
      # version: ""  # Replace with the desired chart version
      sourceRef:
        kind: GitRepository
        name: flux-system  # Refer to the HelmRepository defined above
        namespace: flux-system
      valuesFiles:
        - tomcatcharts/values.yaml

  install:
    createNamespace: true
  rollback:
    force: true
  values: 
    repository: saikiran900/tomcatimage
    # Default environment
    environment: sbx
    pullpolicy: ifNotPresent
    tag: 0.0.2




    
